# Generated by Django 5.2.10 on 2026-02-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
