# Generated by Django 5.2.10 on 2026-02-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_train_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='train',
            name='total_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
