# Generated by Django 5.2.10 on 2026-02-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('passengers', models.IntegerField(default=1)),
                ('passenger_details', models.TextField(blank=True, null=True)),
                ('pnr', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('total_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_bookings', to='trains.train')),
            ],
            options={
                'db_table': 'adminpanel_booking',
            },
        ),
    ]
