# Generated by Django 5.2.10 on 2026-02-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_created_at_booking_from_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.TextField(blank=True, help_text='Comma separated seat numbers', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='CONFIRMED', max_length=20),
        ),
    ]
